spring:
  cloud:
    stream:
      default-binder: rabbit
      default:
        group: initiator
      bindings:
        availabilityReceived-in-0:
          destination: truck-availability-topic
        availability:
          destination: truck-availability-topic
  application:
    name: fleet-management-app
  jpa:
    open-in-view: false
    hibernate.ddl-auto: none
  flyway.enabled: true
springdoc.api-docs.path: /api-docs