apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: wehaul-fleet-management-app
  labels:
    app.kubernetes.io/part-of: wehaul-fleet-management-app
    apps.tanzu.vmware.com/workload-type: web
    # todo: play with this
#    apps.tanzu.vmware.com/has-tests: true
#    apps.tanzu.vmware.com/supply-chain: scanning
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      ref:
        branch: main
      url: https://github.com/santiagovm/tap-hackathon-fleet-management.git
  serviceClaims:
    - name: db
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: postgres-team-a
    - name: queue
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: rmq-shared-team-a